In [ ]:
import numpy as np
import doctest

## Softmax loss

In [ ]:
def softmax_naive(x):
  '''
  >>> x = np.array([0.3, 2.9, 4.0])
  >>> softmax_naive(x)
  array([0.01821127, 0.24519181, 0.73659691])
  '''

  exp_x = np.exp(x)
  sum_exp_x = np.sum(exp_x)
  y = exp_x / sum_exp_x

  return y

In [ ]:
doctest.run_docstring_examples(softmax_naive, globals(), False, __name__)

In [ ]:
numerical_x = np.array([1010, 1000, 990])
print(softmax_naive(numerical_x))

[nan nan nan]


<ipython-input-5-30303a4610ad>:8: RuntimeWarning: overflow encountered in exp
  exp_x = np.exp(x)
<ipython-input-5-30303a4610ad>:10: RuntimeWarning: invalid value encountered in divide
  y = exp_x / sum_exp_x


**'ppp' exercise**

In [ ]:
def softmax_stable(x):
  '''
  >>> x = np.array([1010, 1000, 990])
  >>> softmax_stable(x)
  array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])
  '''
  c = np.max(x)
  exp_x = np.exp(x - c)
  sum_exp_x = np.sum(exp_x)

  y = exp_x / sum_exp_x
  return y

In [ ]:
doctest.run_docstring_examples(softmax_stable, globals(), False, __name__)

**'ppp' exercise**

In [ ]:
def softmax(x):  # mini batch version
  '''
  >>> x = np.array([0.3, 2.9, 4.0])
  >>> softmax(x)
  array([0.01821127, 0.24519181, 0.73659691])
  >>> x = np.array([1010, 1000, 990])
  >>> softmax(x)
  array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])
  >>> x = np.array([
  ...  [0.3, 2.9, 4.0],
  ...  [1010, 1000, 990]
  ...  ])
  >>> softmax(x)
  array([[1.82112733e-02, 2.45191813e-01, 7.36596914e-01],
         [9.99954600e-01, 4.53978686e-05, 2.06106005e-09]])
  '''
  if x.ndim == 2:
    x = x.T
    x = x - np.max(x, axis=0)
    y = np.exp(x) / np.sum(np.exp(x), axis=0)
    return y.T

  x = x - np.max(x)
  return np.exp(x) / np.sum(np.exp(x))

In [ ]:
doctest.run_docstring_examples(softmax, globals(), False, __name__)

In [ ]:
x = np.array([[0.3, 2.9, 4.0], [1010, 1000, 990]])
print(x.shape)
x = x.T
print(x.shape)
print(np.max(x, axis=0).shape)
print((x - np.max(x, axis=0)).shape)

(2, 3)
(3, 2)
(2,)
(3, 2)
